name: Setup Node and Install
description: 'Sets up Node.js 24.2.0 and runs npm ci'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24.2.0

    - run: npm ci
      shell: bash
