name: Setup Node and Install
description: Setup Node.js and install dependencies with npm
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24.2.0

    - run: npm ci
