name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check Prettier formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24.2.0
      - run: npm ci
      - run: npm run check-format

  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24.2.0
      - run: npm ci
      - run: npm run lint

  test:
    name: Run Unit/Component Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24.2.0
      - run: npm ci
      - run: npm test

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [format, lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24.2.0
      - run: npm ci
      - run: docker build -t cozy-cabin-frontend .
