name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check Prettier formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-and-install
      - run: npm run check-format

  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-and-install
      - run: npm run lint

  test:
    name: Run Unit/Component Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-and-install
      - run: npm test

  publish:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [format, lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-and-install
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Show images
        run: docker images
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/cozy-cabin-frontend2:latest .
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/cozy-cabin-frontend2:latest
