name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check Prettier formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npm/action-setup@v2
        with:
          version: 8
      - run: npm install
      - run: npm check-format

  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npm/action-setup@v2
        with:
          version: 8
      - run: npm install
      - run: npm lint

  test:
    name: Run Unit/Component Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npm/action-setup@v2
        with:
          version: 8
      - run: npm install
      - run: npm test

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [format, lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: npm/action-setup@v2
        with:
          version: 8
      - run: npm install
      - run: docker build -t cozy-cabin-frontend .
